In [1]:
%run "Common setup.ipynb"

Because SALib concentrates on GSA methods, we implement our own local OAT methods here.

In [2]:
# problem specification for traditional OAT analysis
oat_spec = {
  'num_vars': 4,
  'names': ['x1', 'x2', 'x3', 'x4'],
  'bounds': [[-np.pi, np.pi]]*4,
  'nominal': [1.0,] * 4
}

In [3]:
OAT_SAMPLES = 5000

<hr>

Traditional OAT approach

In [4]:
oat_samples = traditional_oat_sample(oat_spec, OAT_SAMPLES)
oat_samples

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [-3.14159265,  1.        ,  1.        ,  1.        ],
       [-3.13656208,  1.        ,  1.        ,  1.        ],
       ...,
       [ 1.        ,  1.        ,  1.        ,  3.13153151],
       [ 1.        ,  1.        ,  1.        ,  3.13656208],
       [ 1.        ,  1.        ,  1.        ,  3.14159265]])

In [5]:
Y = ishigami_wrapper(oat_samples)
Y

array([5.88213201, 4.95651393, 4.95098032, ..., 5.88213201, 5.88213201,
       5.88213201])

In [6]:
oat_analyze(oat_spec, oat_samples, Y).mean(axis=0)

array([0.49921414, 1.75941067, 0.36142324, 0.        ])

<hr>

In [7]:
%%timeit
oat_samples = traditional_oat_sample(oat_spec, OAT_SAMPLES)

1.7 ms ± 88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit
Y = Ishigami.evaluate(oat_samples)

16.1 ms ± 339 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%%timeit
oat_analyze(oat_spec, oat_samples, Y).mean(axis=0)

18.3 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


<hr>

OAT of extremeties

In [10]:
extremity_samples = oat_extremity_sample(oat_spec)
extremity_samples

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [-3.14159265,  1.        ,  1.        ,  1.        ],
       [ 3.14159265,  1.        ,  1.        ,  1.        ],
       [ 1.        , -3.14159265,  1.        ,  1.        ],
       [ 1.        ,  3.14159265,  1.        ,  1.        ],
       [ 1.        ,  1.        , -3.14159265,  1.        ],
       [ 1.        ,  1.        ,  3.14159265,  1.        ],
       [ 1.        ,  1.        ,  1.        , -3.14159265],
       [ 1.        ,  1.        ,  1.        ,  3.14159265]])

In [11]:
Y = Ishigami.evaluate(extremity_samples)
Y

array([ 5.88213201,  4.95651393,  4.95651393,  0.92561808,  0.92561808,
       13.99467729, 13.99467729,  5.88213201,  5.88213201])

In [12]:
oat_analyze(oat_spec, extremity_samples, Y).mean(axis=0)

array([-0.10435844, -0.55882018,  0.91464567,  0.        ])

<hr>

In [13]:
%%timeit
extremity_samples = oat_extremity_sample(oat_spec)

14.4 µs ± 358 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%%timeit
Y = Ishigami.evaluate(extremity_samples)

31.3 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [15]:
%%timeit
oat_analyze(oat_spec, extremity_samples, Y).mean(axis=0)

41.8 µs ± 1.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


<hr>